# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Color' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Color

  pod 'SwiftLint'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxGesture'
  pod 'ReactorKit' 


  target 'ColorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ColorUITests' do
    # Pods for testing
  end

end
